### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gogs#10]
after running go get `go get -u github.com/gigforks/gogs`, running `go build` fails on a missing import 
![screenshot from 2017-01-04 14-28-06](https://cloud.githubusercontent.com/assets/22023708/21643849/da4a7f34-d28a-11e6-8a27-07d5d7ecf065.png)

Note: this was on the `itsyouimpl` branch

**Comment by robvanmieghem** [comment]
As said, dependency mgmt is done through glide

**Comment by xmonader** [comment]
First you need to make sure you got glide installed, and cloned the gogits/gogs repo itself. 

then you have to add a remote to `gigforks/gogs` and switch to the branch itsyouimpl  

something like this

```
        curl https://glide.sh/get > installglide.sh
        . installglide.sh

        GOGITSDIR=$GOPATH/src/github.com/gogits
        GOGSDIR=$GOGITSDIR/gogs

        go get golang.org/x/oauth2
        go get github.com/gogits/gogs

        cd $GOGSDIR && git remote add xmonorigin https://github.com/gigforks/gogs && git fetch xmonorigin && git checkout xmonorigin/itsyouimpl

        cd $GOGSDIR && glide install && go build -tags "sqlite cert"
        echo **OK**

```

**Comment by LeeSmet** [comment]
Yes, I installed glide and got it working. Do note however that the `docker build .` command seems to fail.I'm guessing this has something to do with the `docker/build.sh` trying to use go version 1.5.4 and then not finding the `golang.org/x/oauth2` package

**Comment by robvanmieghem** [comment]
https://github.com/gigforks/gogs/commit/f787e3b376e5998964e0435201bda66e685f2bcd
