### ISSUE TITLE
Implement some changes through less instead of in the html

### ISSUE THREAD

**Issue by robvanmieghem** [gigforks/gogs#18]
The changes in the header and footer from https://github.com/gigforks/gogs/commit/4321a92309843d96d83f2cd1441acd774416c0b5 should be implemented in the iyo.less to limit the changes in common files.

**Comment by arahmanhamdy** [comment]
fixed in gigforks/gitea:

The templates and locales now are fully separated in custom repo:
Incubaid/gitea_custom

**Comment by Dinaamagdy** [comment]
solved in gitea  1.0.0
