### ISSUE TITLE
Investigate panic if there are no itsyouonline organizations

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gogs#25]
[Macaron] PANIC: interface conversion: interface {} is nil, not []string
/usr/local/go/src/runtime/panic.go:489 (0x42a8cf)
/usr/local/go/src/runtime/iface.go:172 (0x40d5a1)
/Users/rob/workspace/go/src/github.com/gogits/gogs/routers/api/v1/repo/collaborators_extended.go:33 (0xc23735)

**Comment by arahmanhamdy** [comment]
I need more clarification

**Comment by LeeSmet** [comment]
# The issue

As seen in the original comment: 
`[Macaron] PANIC: interface conversion: interface {} is nil, not []string`
This suggests that somewhere, we attempt to convert an empty interface into a slice of strings using an unchecked type assertion, which does not work. From the last line of the original comment, being: 
`/Users/rob/workspace/go/src/github.com/gogits/gogs/routers/api/v1/repo/collaborators_extended.go:33 (0xc23735)`

We can extract an exact location in the code where this panic is happening (line 33 in routers/api/v1/repo/collaborators_extended.go).

If we take a look at said file, we can indeed see an unchecked type assertion at the aforementioned line number:
https://github.com/gigforks/gogs/blob/feef207e10ab27609c8bf1660207c47294f99aad/routers/api/v1/repo/collaborators_extended.go#L29-L50

# The solution

Further examination from the code indicates that we later range over the slice (after our assertion). Since we use `range`, we already can handle the empty slice here. So we just need some logic to identify an empty interface and get an empty slice out of it.

We know that the assertion fails if the interface is empty. Fortunately, the go language spec has a small section about type assertions describing just this scenario:
https://golang.org/ref/spec#Type_assertions

As described in this document, adding a second variable in the assignment will prevent the assertion from throwing the panic. 
As an added bonus, our initial variable will then contain the zero-value of the asserted type (which happens to be the empty string slice we want).

But like we found out earlier, we can already handle the zero-value. So we don't really care for the result of the assertion. So now the compiler will complain. However, if we dig into the go language spec some more, we find just what we need: 
https://golang.org/doc/effective_go.html#blank

Throwing all of the above together, we come to the following elegant solution:
`userOrgs, _ := ctx.Session.Get("organizations").([]string)`

**Comment by Dinaamagdy** [comment]
solved on gites version 1.0.0 at f76784f3c51474c9dca3e5bf3ed3b5a1a3baba2e
