### ISSUE TITLE
Many of the gig members (gogs) can't access the gig_team repo

### ISSUE THREAD

**Issue by yveskerwyn** [gigforks/gogs#27]
Both @hassane and @adelsamar can't access gig_team while there are both member of the gig organization

Trying to grant them access explicitly doesn't work, you'll get an error that they are already member of the organization...

Originally filed: https://docs.greenitglobe.com/gig/org_support/issues/272

**Comment by yveskerwyn** [comment]
Strange since both are already member at the gig organization:
https://docs.greenitglobe.com/org/gig/members

![screen shot 2017-06-06 at 13 40 14](https://cloud.githubusercontent.com/assets/13795109/26827475/bde7ac26-4abd-11e7-8ca5-0da66c54614a.png)

**Comment by yveskerwyn** [comment]
Probably because there are not member of the development team?
See: https://docs.greenitglobe.com/org/gig/teams/development

**Comment by yveskerwyn** [comment]
When trying (first screenshot) to explicitly adding @hassane I get error:
`User is organization member who cannot be added as a collaborator.`
![screen shot 2017-06-06 at 13 50 14](https://cloud.githubusercontent.com/assets/13795109/26827804/1fbc0a72-4abf-11e7-8d99-be6efecf082e.png)




![screen shot 2017-06-06 at 13 52 05](https://cloud.githubusercontent.com/assets/13795109/26827845/48bba482-4abf-11e7-99c5-83500c233a8d.png)

**Comment by yveskerwyn** [comment]
So as it turns out:

We had to grant write access to the IYO organization `greenitglobe.development`

AND 

Both users need to be member of this IYO organixation, which was only the case for @adelsamar

**Comment by LeeSmet** [comment]
Access rights on gogs require users to be part of a team as well to view the private repos of an organization. 

Workaround: add the `greenitglobe.development` organization as collaborator to the repo (already done in the last pictures), and then make sure the users are part of this organization on ItsYou.Online aswell

**Comment by samaradel** [comment]
Me and @hassane can't clone gig_team repo

**Comment by LeeSmet** [comment]
This is probably related to this bug: https://github.com/gigforks/gogs/issues/28. If so, someone with the right access rights will need to configure this organization/repo so that the affected users have access through gogs own grouping system as a workaround

**Comment by arahmanhamdy** [comment]
duplicate #28
