### ISSUE TITLE
ItsYou.online integration on repo access not working as expected

### ISSUE THREAD

**Issue by LeeSmet** [gigforks/gogs#29]
Original issue: https://github.com/itsyouonline/identityserver/issues/525

Please note that, because gogs uses its own group management system, and ItsYou.online has no way of notifying gogs of organizational changes, a deliberate choice was made to only expose the itsyouonline membership during the repo access check. Therefore users who have been added only by means of an itsyou online organization membership will not see the repo in their account overview etc...

Connecting to (private) repo's needs to happen by manually entering (or pasting, ...) the exact url in the browser

for documentation( note that this is the itsyouonlineimpl branch ): https://github.com/gigforks/gogs/blob/itsyouimpl/itsyouonline.md

**Comment by arahmanhamdy** [comment]
fixed in gigforks/gitea: 
While the user logging, the iyo organizations that user belongs to are saved in the session, so we can query related repos when viewing the homepage

there is no current cleaner fix because of the scope limitation of itsyou.online

**Comment by Dinaamagdy** [comment]
fixed in gitea 1.0.0
