### ISSUE TITLE
Integrate itsyou.online organizations

### ISSUE THREAD

**Issue by robvanmieghem** [gigforks/gogs#8]

**Comment by rkhamis** [comment]
@robvanmieghem did you check the https://github.com/gigforks/gogs/tree/itsyouimpl branch?

**Comment by robvanmieghem** [comment]
@rkhamis yes but the only commit I found regarding organizations is https://github.com/gigforks/gogs/commit/00561f3584002e16815ad60122142800b5bdd5bf
How does this integrate with authorizing itsyou.online organizations in the gogs permissions?

**Comment by daliusl** [comment]
There is already team created "support-team" gig Gogs, but it will not be correct as it will have to be greenitglobe.operations (probably has to be updated to gig.operations)

**Comment by robvanmieghem** [comment]
Just to avoid confusion, the intention of this ticket is to be able to not only have people added to projects/repo's in gogs but also itsyou.online organizations. This way all members of the itsyou.online organization have access to the repo and there is no need to manage individual membership in gogs.
